version: "3.3"
services:

  avia:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: avia
    ports:
      - 4203:4200
    container_name: avia
    restart: on-failure
    command: ng serve --host 0.0.0.0 --port 4200 --disable-host-check

